import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Layout } from '@/components/Layout'
import { ProductCard } from '@/components/ProductCard'
import { chair, products, productCategories } from '@/data/products'
import { useCart } from '@/features/cart'
import { money } from '@/shared/lib/format'
import { Icon } from '@/shared/ui/Icons'

export function ProductPage(){
 const {productId}=useParams()
 const product=products.find(item=>item.id===productId)||chair
 const category=productCategories.find(item=>item.slug===product.category)
 const gallery=useMemo(()=>{const related=products.filter(item=>item.category===product.category&&item.id!==product.id).map(item=>item.image);return [product.image,...related,...products.map(item=>item.image)].slice(0,4)},[product])
 const recommendations=products.filter(item=>item.id!==product.id).slice(0,4)
 const [active,setActive]=useState(0),[qty,setQty]=useState(1),[color,setColor]=useState(0),[open,setOpen]=useState(null),[status,setStatus]=useState('idle'); const {addItem}=useCart()
 useEffect(()=>{document.title=`${product.name} | Mộc Nhà`},[product])
 const add=()=>{setStatus('loading');setTimeout(()=>{for(let i=0;i<qty;i++)addItem(product);setStatus('done');setTimeout(()=>setStatus('idle'),1800)},500)}
 const step=(n)=>setActive((active+n+gallery.length)%gallery.length)
 return <Layout><script type="application/ld+json">{JSON.stringify({'@context':'https://schema.org','@type':'Product',name:product.name,image:product.image,description:product.description,offers:{'@type':'Offer',price:product.price,priceCurrency:'VND',availability:'https://schema.org/InStock'},aggregateRating:{'@type':'AggregateRating',ratingValue:4.9,reviewCount:32}})}</script><div className="container product-page"><nav className="breadcrumb"><Link to="/">Trang chủ</Link> / <Link to={`/san-pham/${product.category}`}>{category?.label||'Sản phẩm'}</Link> / {product.name}</nav><section className="product-detail"><div className="gallery" tabIndex="0" onKeyDown={e=>{if(e.key==='ArrowLeft')step(-1);if(e.key==='ArrowRight')step(1)}}><div className="main-image"><img src={gallery[active]} alt={`${product.name} - ảnh ${active+1}`}/><button className="prev" onClick={()=>step(-1)} aria-label="Ảnh trước">‹</button><button className="next" onClick={()=>step(1)} aria-label="Ảnh sau">›</button></div><div className="thumbs">{gallery.map((img,i)=><button key={`${img}-${i}`} className={i===active?'active':''} onClick={()=>setActive(i)}><img src={img} alt={`Ảnh nhỏ ${i+1} của ${product.name}`}/></button>)}</div></div>
 <div className="product-info"><h1>{product.name}</h1><div className="stars">★★★★★ <span>4.9 (32 đánh giá) | Đã bán 128 sản phẩm</span></div><p>{product.description}. Sản phẩm được hoàn thiện tỉ mỉ từ chất liệu chọn lọc, mang đến vẻ đẹp bền vững và cảm giác gần gũi cho không gian sống.</p><div className="detail-price">{money(product.price)}</div><b>Màu sắc / Chất liệu</b><div className="color-options">{product.colors.map((c,i)=><button className={color===i?'active':''} onClick={()=>setColor(i)} key={c}><i style={{background:c}}/><span>{['Màu tự nhiên','Màu trung tính','Màu trầm'][i]}</span></button>)}</div><div className="quantity"><b>Số lượng</b><div><button onClick={()=>setQty(Math.max(1,qty-1))}>−</button><span>{qty}</span><button onClick={()=>setQty(qty+1)}>＋</button></div></div><div className="detail-actions"><button className="btn olive" onClick={add} disabled={status==='loading'}><Icon name={status==='done'?'check':'cart'}/>{status==='loading'?'Đang thêm...':status==='done'?'Đã thêm vào giỏ':'Thêm vào giỏ hàng'}</button><button className="btn outline">Mua ngay</button></div><div className="mini-benefits"><span><Icon name="truck" size={24}/><b>Miễn phí giao hàng toàn quốc</b><small>Cho đơn hàng từ 5.000.000đ</small></span><span><Icon name="leaf" size={24}/><b>14 ngày đổi trả</b><small>An tâm mua sắm</small></span></div><div className="accordions">{[['Mô tả sản phẩm',`${product.name} được thiết kế theo tinh thần tối giản, chú trọng công năng và độ bền.`],['Kích thước & chất liệu','Kích thước được tối ưu cho không gian sống hiện đại. Chất liệu tự nhiên, hoàn thiện thủ công.'],['Hướng dẫn bảo quản','Lau nhẹ bằng khăn mềm, tránh ánh nắng trực tiếp và môi trường ẩm kéo dài.'],['Giao hàng & đổi trả','Giao hàng toàn quốc và hỗ trợ đổi trả trong vòng 14 ngày.']].map(([t,c],i)=><div key={t}><button onClick={()=>setOpen(open===i?null:i)}>{t}<Icon name={open===i?'minus':'plus'}/></button><p className={open===i?'open':''}>{c}</p></div>)}</div></div></section>
 <section className="editorial"><div><img src={product.image} alt={`${product.name} trong không gian Mộc Nhà`}/></div><article><h2>Thiết kế cho<br/>cuộc sống an yên</h2><p>{product.name} là sự kết hợp hài hòa giữa thẩm mỹ tối giản và công năng tiện nghi. Từng đường nét được chăm chút với chất liệu gần gũi thiên nhiên.</p><div>{[['leaf','Chất liệu tự nhiên'],['heart','Thiết kế tinh tế'],['shield','Bền vững dài lâu']].map(x=><span key={x[1]}><Icon name={x[0]} size={28}/><b>{x[1]}</b></span>)}</div></article></section>
 <section className="section recommendations"><div className="section-head"><h2>Có thể bạn cũng thích</h2><Link to="/san-pham">Xem tất cả →</Link></div><div className="product-grid">{recommendations.map(item=><ProductCard key={item.id} product={item} compact/>)}</div></section></div></Layout>
}
